export const categories = [
  { value: "electronics", label: "Electronics" },
  { value: "fashion", label: "Fashion & Apparel" },
  { value: "food", label: "Food & Grocery" },
  { value: "home", label: "Home & Living" },
  { value: "beauty", label: "Beauty" },
  { value: "health", label: "Health" },
  { value: "sports", label: "Sports & Outdoors" },
  { value: "toys", label: "Kids & Toys" },
  { value: "automotive", label: "Automotive" },
  { value: "art", label: "Hobbies & Music" },
  { value: "books", label: "Books & Office" },
  { value: "hardware", label: "Tools" },
  { value: "pets", label: "Pets" },
  { value: "jewelry", label: "Jewelry" },
  { value: "gifts", label: "Gifts" },
  { value: "digital", label: "Digital" },
];
