export const categories = [
  { value: "electronics", label: "Electronics & Gadgets" },
  { value: "fashion", label: "Fashion & Apparel" },
  { value: "food", label: "Food, Grocery & Restaurants" },
  { value: "home", label: "Home, Furniture & Garden" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "health", label: "Health, Medical & Pharmacy" },
  { value: "sports", label: "Sports, Fitness & Outdoors" },
  { value: "toys", label: "Toys, Kids & Baby" },
  { value: "automotive", label: "Automotive & Accessories" },
  { value: "art", label: "Art, Crafts & Music" },
  { value: "books", label: "Books, Office & Stationery" },
  { value: "hardware", label: "Hardware & Tools" },
  { value: "pets", label: "Pet Supplies & Services" },
  { value: "jewelry", label: "Jewelry & Watches" },
  { value: "gifts", label: "Gifts & Specialty Items" },
  { value: "digital", label: "Digital Products & Services" },
];
