import "./global.css";

import { Poppins } from "next/font/google";
import Provider from "./provider";

export const metadata = {
  title: "Ccius - Admin",
  description: "Generated by create-nx-workspace",
};

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`min-h-screen bg-slate-900 font-sans antialiased ${poppins.variable}`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
